# Generated by Django 2.2.14 on 2021-04-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
    ]
