# Generated by Django 2.2.14 on 2021-04-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
