# Generated by Django 2.2.14 on 2021-04-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_refund_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_accepted',
        ),
    ]
